### ISSUE TITLE
php的匿名function有一個use，沒有正確翻譯出來

### ISSUE THREAD

**Issue by zaoqi** [max-team/ts2php#1]

**Comment by cxtom** [comment]
你是说这种吗？
```php
$a = 1;
$b = function () use ($a) {
       $c = $a + 1;
}
```

**Comment by zaoqi** [comment]
是。enum的翻譯好像也有點問題。所以我當時先編譯為ES6，然後用 https://gitlab.com/the-language/the-language/blob/30a7bfda0767731504e5a8462a13225dca71db4f/core/arch/php/compile.js
源 https://gitlab.com/the-language/the-language/blob/30a7bfda0767731504e5a8462a13225dca71db4f/core/arch/typescript/lang.ts
輸出 https://gitlab.com/the-language/the-language/blob/30a7bfda0767731504e5a8462a13225dca71db4f/core/arch/php/lang.php

**Comment by zaoqi** [comment]
可能需要`use (&$x)`

**Comment by cxtom** [comment]
这两个都还没做，感谢建议～

**Comment by zaoqi-unsafe** [comment]
typescript的编译器文档在哪里?
```
import * as ts from 'typescript';
```
