### ISSUE TITLE
全局變量

### ISSUE THREAD

**Issue by zaoqi** [max-team/ts2php#35]
全局變量不能正常工作。
需要`global $...`

**Comment by zaoqi** [comment]
```
var x=0;
function f(){
return x;}
```

**Comment by cxtom** [comment]
这种情况没想到好的办法支持

**Comment by zaoqi** [comment]
也許可以把全局放到一個函數裏，然後進行某些處理。

**Comment by zaoqi-unsafe** [comment]
@cxtom 
情況和閉包類似。應該可以用類似的算法。
應該也可以用use。
可以把函數存入同名全局變量，生成一個同名PHP函數來調用這個全局變量。 或者把use改爲global。

**Comment by zaoqi** [comment]
是已经修复了吗？
