### ISSUE TITLE
字符串 replace 方法参数不支持 函数

### ISSUE THREAD

**Issue by l5oo00** [max-team/ts2php#68]
ts 里写 replace 方法传了个函数， 发现 ts2php 编译期能正常转换， 到 php 运行时才报错， 是否可以直接在编译期报错？

**Comment by meixg** [comment]
可以给一下代码片段么？
意思是不是这种情况下的编译错误？
```typescript
function aaa() {
}

str.replace('abc', aaa);
```

**Comment by l5oo00** [comment]
对， 或者直接一个匿名函数， 我之前看编译是 OK 的， 但是编译后的语法在测试机上不支持， 如果确定不支持的话， 我建议： 

- readme 文档里加上说明
- 编译期直接报错

不知道是否可行？

**Comment by meixg** [comment]
4e0641ce7fbe93b346e28615e4e6c87fe21c548b
readme 中添加了相关说明，编译期现在会报错了。

后续考虑一下函数形式能不能支持。
