### ISSUE TITLE
默认移除类型的 import

### ISSUE THREAD

**Issue by harttle** [max-team/ts2php#8]
import 会被翻译成 require_once，但是在 TypeScript 中会有一些 import 只是为了类型信息的。因为翻译后代码中没有引用，所以可以默认不产出这些 require_once。

**Comment by cxtom** [comment]
需要在输出 require_once 之前，先把 TypeNode 都过滤掉，如果为空就不输出 require_once
https://github.com/max-team/ts2php/blob/master/src/emitter.ts#L1933
