### ISSUE TITLE
代码风格检查（linting)

### ISSUE THREAD

**Issue by harttle** [max-team/ts2php#9]
缺少 lint 配置和工具，多人协作时会很难受

**Comment by meixg** [comment]
cb3104dafed240cc7d7a199cf74253fce88f8a12
配置了 eslint
使用 vscode 时，可以：

- 将 .vscode/setting.template.json 改成 setting.json 

或者

- 将 .vscode/setting.template.json 中的内容复制到自己的 setting.json 文件中

来开启 eslint 检查。

发现代码风格问题非常多，目前没有设置成强制，后续修改完成后加入流水线检查。
