### ISSUE TITLE
是否可以把 class 上所有的静态方法和属性都延迟赋值？

### ISSUE THREAD

**Issue by l5oo00** [max-team/ts2php#94]
php 中初始化类时它的属性值只能是常量([文档说明](https://www.php.net/manual/zh/language.oop5.properties.php))， 而我们写  ts 经常会有如下代码：

```typescript
const a = 'x';
class Demo {
    static x = a // a 是变量， 转换成 PHP 后会挂掉
}
```

[之前](https://github.com/searchfe/san-ssr/issues/16)的做法是将 static 属性延迟初始化， 想着 ts2php 是不是默认可以做这个事情，即将所有 static 的属性延迟初始化。

**Comment by meixg** [comment]
初始化值不为数字或字符串时，都会编译为延迟赋值。
其他字面量不好判断，内部可能包含变量，需要遍历，例如 [a]。
